# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx
r_build_args: --no-build-vignettes
r_check_args: --as-cran --ignore-vignettes

sudo: true
cache: packages

matrix:
  exclude:
  - os: osx
    r: devel

r_packages:
  - covr

before_install:
- Rscript -e 'install.packages(cairo)'

after_success:
  - Rscript -e 'covr::codecov()'
